[profile.default]
src = "packages"
out = "out"
solc = "0.8.26"
optimizer = true
optimizer_runs = 8000
via_ir = true
evm_version = "paris"

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "all"
quote_style = "double"
tab_width = 2
wrap_comments = true

[profile.compliance-token-erc20]
src = 'packages/token/erc-20/src'
test = 'packages/token/erc-20/test'

[profile.compliance-token-erc3643]
src = 'packages/token/erc-3643/src'
test = 'packages/token/erc-3643/test'

[profile.policy-management]
src = 'packages/policy-management/src'
test = 'packages/policy-management/test'

[profile.cross-chain-identity]
src = 'packages/cross-chain-identity/src'
test = 'packages/cross-chain-identity/test'
